version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

executors:
  default-go:
    docker:
      - image: golang:1
        environment:
          GOPATH: /go

workflows:
  tests_and_linters:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          executor-name:
            name: default-go
          context: cm-team-github
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
          context: cm-team-github
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context:
            - cm-team-snyk
            - cm-team-github
