version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@2

workflows:
  tests_and_linters:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          context: dockerhub-shared
